version: '3'
services: 
    db:
        image: postgres
        volumes: 
            - postgres-data:/var/lib/postgresql/data
        environment: 
            - POSTGRES_HOST=$DB_HOST
            - POSTGRES_USER=$DB_USER
            - POSTGRES_PASSWORD=$DB_PASSWORD
        ports:
            - $DB_PORT:$DB_PORT
    web:
        build:
            context: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes:
            - .:/$WORKDIR
        environment: 
            - TZ=$TZ
            - POSTGRES_HOST=$DB_HOST
            - POSTGRES_USER=$DB_USER
            - POSTGRES_PASSWORD=$DB_PASSWORD
        ports:
            - $API_PORT:$CONTAINER_PORT
        depends_on:
            - db
        tty: true
        stdin_open: true
volumes:
    postgres-data:
        driver: local